services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: investimento-back-api
    container_name: api
    depends_on: [ db ]
    ports:
      - 8080:8080
    restart: always
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data3
volumes:
  pgdata: